### ISSUE TITLE
Windows path does not create specified directory 

### ISSUE THREAD

**Issue by bijoy26** [Arnab-Shanta-Anu/download-all-repos#15]
### Machine Configuration
**OS:** Windows 10 (64 bit)
**Processor:** Intel Core i5-3470 3.2GHz
**RAM:** 8 GB 

While being prompted to put the **Directory Name** in order to clone all the repos into, it does not recognize if a new directory is given or not.
Instead, it clones all the repos into **Desktop** (which is specified as *default directory* in the code).
Trying with other valid directories also produces the same result.

## Steps to reproduce:
1. Boot from *Windows 10* system
2. Check if your Windows *User* has space or not. (Ex - *"Abdul Karim"*)
3. Give an absolute path with a new directory name (Ex- _"C:\Users\Anjum Rashid\Desktop\AllRepo"_)

![s1](https://user-images.githubusercontent.com/42487891/81216030-0e241e00-8ffc-11ea-8a34-c59808d5e8a6.jpg)

4. Check your Desktop folder to find the downloaded repos there.

![s2](https://user-images.githubusercontent.com/42487891/81216168-49bee800-8ffc-11ea-82ad-52b4e845183c.jpg)

## Recommendations
The issue might be associated with **directories with spaces** in their path.
It is also possible it might be occurring due to something related with **mkdir command** in the code.

**Comment by Arnab-Shanta-Anu** [comment]
working on it. the problem is with os.mkdir indeed
